name: Publish NPM Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (leave empty for package.json version)'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci --only=production || npm install --only=production
        
      - name: Update version if specified
        if: github.event.inputs.version != ''
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version
        
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release (if manual)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version || 'auto' }}
          release_name: Release v${{ github.event.inputs.version || 'auto' }}
          body: |
            ## 📦 NPM Package Published
            
            This release includes the NPM package for one-click installation:
            
            ```bash
            npm install -g @clippymcp/windows-clippy-mcp
            ```
            
            ### What's New
            - One-click NPM installation support
            - Automated VS Code configuration
            - Windows service integration
            - Both NPM and traditional installation methods supported
            
            See [NPM-INSTALL.md](NPM-INSTALL.md) for complete installation instructions.
          draft: false
          prerelease: false